version: 2

sources:
  - name: staging
    database: de-course-411516
     # For postgres:
      #database: production
    schema: terraform_dataset

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata_non_partitoned
      - name: yellow_tripdata_non_partitoned
         # freshness:
           # error_after: {count: 6, period: hour}