version: 2

sources:
  - name: staging
    database: de-course-411516
     # For postgres:
      #database: production
    schema: terraform_dataset

      # loaded_at_field: record_loaded_at
    tables:
      - name: taxi_zone_non_partitoned